In [ ]:
# import torch
# torch.cuda.is_available()

False

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# import os
# os.listdir("/content/drive/MyDrive")

['stubble_vision']

In [ ]:
# os.listdir("/content/drive/MyDrive/stubble_vision/data/raw")

['viirs_punjab.csv']

In [ ]:
import os
import pandas as pd

# Define raw data directory
CSV_DIR = "/content/drive/MyDrive/stubble_vision/data/raw"

# 1️⃣ Check directory exists
if not os.path.exists(CSV_DIR):
    raise FileNotFoundError(f"❌ Directory does not exist: {CSV_DIR}")

# 2️⃣ List files
files = os.listdir(CSV_DIR)
print("Files found:", files)

# 3️⃣ Filter CSV files
csv_files = [f for f in files if f.lower().endswith(".csv")]

# 4️⃣ Handle no-CSV case safely
if len(csv_files) == 0:
    raise FileNotFoundError(
        f"❌ No CSV files found in {CSV_DIR}. "
        "Please make sure your FIRMS CSV is inside data/raw."
    )

# 5️⃣ Load first CSV (or change index if needed)
csv_file = csv_files[0]
csv_path = os.path.join(CSV_DIR, csv_file)

df = pd.read_csv(csv_path)

print("✅ CSV loaded successfully!")
print("File name:", csv_file)
print("Shape (rows, columns):", df.shape)

# Optional sanity check
df.head()

Files found: ['viirs_punjab.csv']
✅ CSV loaded successfully!
File name: viirs_punjab.csv
Shape (rows, columns): (4353, 14)

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,28.35642,76.14301,335.23,0.52,0.41,2025-11-01,746,N,VIIRS,n,2.0NRT,304.11,2.04,D
1,28.35764,76.14528,331.44,0.52,0.41,2025-11-01,746,N,VIIRS,n,2.0NRT,302.41,3.06,D
2,29.09356,77.48702,333.13,0.44,0.38,2025-11-01,746,N,VIIRS,n,2.0NRT,302.25,3.27,D
3,29.20996,77.63349,338.85,0.43,0.38,2025-11-01,746,N,VIIRS,n,2.0NRT,301.33,1.84,D
4,29.24997,75.99911,332.38,0.51,0.41,2025-11-01,746,N,VIIRS,n,2.0NRT,301.17,3.41,D

In [ ]:
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,28.35642,76.14301,335.23,0.52,0.41,2025-11-01,746,N,VIIRS,n,2.0NRT,304.11,2.04,D
1,28.35764,76.14528,331.44,0.52,0.41,2025-11-01,746,N,VIIRS,n,2.0NRT,302.41,3.06,D
2,29.09356,77.48702,333.13,0.44,0.38,2025-11-01,746,N,VIIRS,n,2.0NRT,302.25,3.27,D
3,29.20996,77.63349,338.85,0.43,0.38,2025-11-01,746,N,VIIRS,n,2.0NRT,301.33,1.84,D
4,29.24997,75.99911,332.38,0.51,0.41,2025-11-01,746,N,VIIRS,n,2.0NRT,301.17,3.41,D

In [ ]:
df.columns

Index(['latitude', 'longitude', 'bright_ti4', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_ti5', 'frp', 'daynight'],
      dtype='object')

In [ ]:
# map VIIRS confidence to numeric
confidence_map = {
    "l": 30,
    "n": 70,
    "h": 100
}

df["confidence_num"] = df["confidence"].map(confidence_map)

# create fire / no-fire label
df["label"] = (df["confidence_num"] >= 70).astype(int)

# verify
df[["confidence", "confidence_num", "label"]].head()

  confidence  confidence_num  label
0          n              70      1
1          n              70      1
2          n              70      1
3          n              70      1
4          n              70      1

In [ ]:
df["label"].value_counts()

label
1    4122
0     231
Name: count, dtype: int64

In [ ]:
# columns we want to keep
keep_cols = [
    "latitude",
    "longitude",
    "bright_ti4",
    "bright_ti5",
    "frp",
    "acq_date",
    "daynight",
    "confidence_num",
    "label"
]

df_clean = df[keep_cols].copy()

df_clean.head()

,latitude,longitude,bright_ti4,bright_ti5,frp,acq_date,daynight,confidence_num,label
0,28.35642,76.14301,335.23,304.11,2.04,2025-11-01,D,70,1
1,28.35764,76.14528,331.44,302.41,3.06,2025-11-01,D,70,1
2,29.09356,77.48702,333.13,302.25,3.27,2025-11-01,D,70,1
3,29.20996,77.63349,338.85,301.33,1.84,2025-11-01,D,70,1
4,29.24997,75.99911,332.38,301.17,3.41,2025-11-01,D,70,1

In [ ]:
df_clean.isnull().sum()

latitude          0
longitude         0
bright_ti4        0
bright_ti5        0
frp               0
acq_date          0
daynight          0
confidence_num    0
label             0
dtype: int64

In [ ]:
df_clean["label"].value_counts()

label
1    4122
0     231
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_df, temp_df = train_test_split(
    df_clean,
    test_size=0.30,
    random_state=42,
    stratify=df_clean["label"]
)

print("Train shape:", train_df.shape)
print("Temp shape:", temp_df.shape)

Train shape: (3047, 9)
Temp shape: (1306, 9)

In [ ]:
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["label"]
)

print("Validation shape:", val_df.shape)
print("Test shape:", test_df.shape)

Validation shape: (653, 9)
Test shape: (653, 9)

In [ ]:
print("Train labels:\n", train_df["label"].value_counts())
print("\nValidation labels:\n", val_df["label"].value_counts())
print("\nTest labels:\n", test_df["label"].value_counts())

Train labels:
 label
1    2885
0     162
Name: count, dtype: int64

Validation labels:
 label
1    619
0     34
Name: count, dtype: int64

Test labels:
 label
1    618
0     35
Name: count, dtype: int64

In [ ]:
BASE_DIR = "/content/drive/MyDrive/stubble_vision/data/processed"

train_df.to_csv(f"{BASE_DIR}/train.csv", index=False)
val_df.to_csv(f"{BASE_DIR}/val.csv", index=False)
test_df.to_csv(f"{BASE_DIR}/test.csv", index=False)

print("✅ Train / Validation / Test CSV files saved")

✅ Train / Validation / Test CSV files saved

In [ ]:
import os
os.listdir(BASE_DIR)

['train.csv', 'val.csv', 'test.csv']

In [ ]:
# features we will use
feature_cols = [
    "bright_ti4",
    "bright_ti5",
    "frp"
]

X_train = train_df[feature_cols]
y_train = train_df["label"]

X_val = val_df[feature_cols]
y_val = val_df["label"]

X_test = test_df[feature_cols]
y_test = test_df["label"]

print("Features selected:", feature_cols)

Features selected: ['bright_ti4', 'bright_ti5', 'frp']

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=10000)

model.fit(X_train, y_train)

print("✅ Model training complete")

✅ Model training complete

In [ ]:
val_accuracy = model.score(X_val, y_val)
print("Validation Accuracy:", val_accuracy)

Validation Accuracy: 0.9433384379785605

In [ ]:
test_accuracy = model.score(X_test, y_test)
print("Test Accuracy:", test_accuracy)

Test Accuracy: 0.9418070444104135

In [ ]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

In [ ]:
y_test_pred = model.predict(X_test)

In [ ]:
print(classification_report(y_test, y_test_pred, target_names=["No Fire", "Fire"]))

              precision    recall  f1-score   support

     No Fire       0.38      0.14      0.21        35
        Fire       0.95      0.99      0.97       618

    accuracy                           0.94       653
   macro avg       0.67      0.56      0.59       653
weighted avg       0.92      0.94      0.93       653

In [ ]:
!pip install -q earthengine-api

In [ ]:
import ee
ee.Authenticate()

True

In [ ]:
import ee

ee.Initialize(project="stubble-vision-ee")
print("✅ Earth Engine initialized successfully")

✅ Earth Engine initialized successfully

In [ ]:
point = ee.Geometry.Point([76.143, 28.356])

s2 = (
    ee.ImageCollection("COPERNICUS/S2_SR")
    .filterBounds(point)
    .filterDate("2023-10-01", "2023-10-31")
    .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 20))
)

print("Number of Sentinel-2 images:", s2.size().getInfo())

/usr/local/lib/python3.12/dist-packages/ee/deprecation.py:207: DeprecationWarning:

Attention required for COPERNICUS/S2_SR! You are using a deprecated asset.
To make sure your code keeps working, please update it.
Learn more: https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR

  warnings.warn(warning, category=DeprecationWarning)

Number of Sentinel-2 images: 5

In [ ]:
import ee
from datetime import datetime, timedelta

# Fire info (example)
lat, lon = 28.356, 76.143
fire_date = "2025-11-01"

point = ee.Geometry.Point([lon, lat])
fire_dt = datetime.strptime(fire_date, "%Y-%m-%d")

In [ ]:
# Time windows
pre_start  = (fire_dt - timedelta(days=30)).strftime("%Y-%m-%d")
pre_end    = (fire_dt - timedelta(days=5)).strftime("%Y-%m-%d")

post_start = (fire_dt + timedelta(days=1)).strftime("%Y-%m-%d")
post_end   = (fire_dt + timedelta(days=10)).strftime("%Y-%m-%d")

In [ ]:
s2 = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
    .filterBounds(point)
    .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 20))
)

In [ ]:
pre_fire = (
    s2.filterDate(pre_start, pre_end)
      .sort("CLOUDY_PIXEL_PERCENTAGE")
      .first()
)

print("Pre-fire image found:", pre_fire is not None)

Pre-fire image found: True

In [ ]:
post_fire = (
    s2.filterDate(post_start, post_end)
      .sort("CLOUDY_PIXEL_PERCENTAGE")
      .first()
)

print("Post-fire image found:", post_fire is not None)

Post-fire image found: True

In [ ]:
# Select NIR and SWIR bands
pre_bands  = pre_fire.select(["B8", "B12"])
post_bands = post_fire.select(["B8", "B12"])

In [ ]:
# Compute NBR for pre-fire image
nbr_pre = pre_bands.normalizedDifference(["B8", "B12"]).rename("NBR_pre")

# Compute NBR for post-fire image
nbr_post = post_bands.normalizedDifference(["B8", "B12"]).rename("NBR_post")

In [ ]:
# dNBR = pre - post
dnbr = nbr_pre.subtract(nbr_post).rename("dNBR")

In [ ]:
# Fire location buffer (meters)
buffer_m = 500   # you can later test 500m, 1km, etc.

fire_area = ee.Geometry.Point([lon, lat]).buffer(buffer_m)

In [ ]:
dnbr_mean = dnbr.reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=fire_area,
    scale=20,        # Sentinel-2 SWIR resolution
    maxPixels=1e9
)

dnbr_value = dnbr_mean.get("dNBR").getInfo()
print("Mean dNBR:", dnbr_value)

Mean dNBR: -0.02982601876621879

In [ ]:
def classify_severity(dnbr):
    if dnbr < 0.10:
        return "Unburned"
    elif dnbr < 0.27:
        return "Low"
    elif dnbr < 0.44:
        return "Moderate"
    else:
        return "High"

severity = classify_severity(dnbr_value)
print("Fire severity:", severity)

Fire severity: Unburned

In [ ]:
fire_events = df[df["label"] == 1].copy()
print("Total fire events:", len(fire_events))

Total fire events: 4122

In [ ]:
from datetime import datetime, timedelta
import ee

def compute_fire_severity(lat, lon, fire_date, buffer_m=500):
    try:
        point = ee.Geometry.Point([lon, lat])
        fire_dt = datetime.strptime(fire_date, "%Y-%m-%d")

        # ---- Time windows ----
        pre_start  = (fire_dt - timedelta(days=30)).strftime("%Y-%m-%d")
        pre_end    = (fire_dt - timedelta(days=5)).strftime("%Y-%m-%d")
        post_start = (fire_dt + timedelta(days=1)).strftime("%Y-%m-%d")
        post_end   = (fire_dt + timedelta(days=10)).strftime("%Y-%m-%d")

        # ---- Sentinel-2 collection ----
        s2 = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(point)
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 20))
        )

        pre = s2.filterDate(pre_start, pre_end).sort("CLOUDY_PIXEL_PERCENTAGE").first()
        post = s2.filterDate(post_start, post_end).sort("CLOUDY_PIXEL_PERCENTAGE").first()

        if pre is None or post is None:
            return None, "No Image"

        # ---- Compute NBR ----
        nbr_pre = pre.normalizedDifference(["B8", "B12"])
        nbr_post = post.normalizedDifference(["B8", "B12"])

        # ---- Compute dNBR (IMPORTANT: rename band) ----
        dnbr = nbr_pre.subtract(nbr_post).rename("dNBR")

        # ---- Buffer around fire ----
        area = point.buffer(buffer_m)

        # ---- Reduce to mean dNBR ----
        dnbr_dict = dnbr.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=area,
            scale=20,
            maxPixels=1e9,
            bestEffort=True
        ).getInfo()

        if dnbr_dict is None or "dNBR" not in dnbr_dict:
            return None, "No Data"

        dval = dnbr_dict["dNBR"]

        # ---- Severity classification ----
        if dval < 0.10:
            severity = "Unburned / Recovered"
        elif dval < 0.27:
            severity = "Low"
        elif dval < 0.44:
            severity = "Moderate"
        else:
            severity = "High"

        return dval, severity

    except Exception as e:
        return None, f"Error: {e}"

In [ ]:
results = []

fire_events = df[df["label"] == 1].copy()

for idx, row in fire_events.head(100).iterrows():
    dnbr_val, severity = compute_fire_severity(
        row["latitude"],
        row["longitude"],
        row["acq_date"]
    )

    results.append({
        "index": idx,
        "latitude": row["latitude"],
        "longitude": row["longitude"],
        "fire_date": row["acq_date"],
        "dNBR": dnbr_val,
        "severity": severity
    })

    print(f"[{idx}] dNBR={dnbr_val}, severity={severity}")

[0] dNBR=-0.030837065833754448, severity=Unburned / Recovered
[1] dNBR=-0.015824437075709116, severity=Unburned / Recovered
[2] dNBR=-0.020709029757102825, severity=Unburned / Recovered
[3] dNBR=0.022080862919853943, severity=Unburned / Recovered
[4] dNBR=0.2531020275872906, severity=Low
[5] dNBR=0.1688115554359553, severity=Low
[6] dNBR=0.24453826009435156, severity=Low
[7] dNBR=0.1939132397822736, severity=Low
[8] dNBR=0.19723350028840775, severity=Low
[9] dNBR=0.20946787497002786, severity=Low
[10] dNBR=0.21402027758903797, severity=Low
[11] dNBR=0.20884207927564233, severity=Low
[12] dNBR=0.16129380560328016, severity=Low
[13] dNBR=0.10734013031150426, severity=Low
[15] dNBR=0.1435667554676517, severity=Low
[16] dNBR=0.21710554129661225, severity=Low
[17] dNBR=0.24813933773572855, severity=Low
[18] dNBR=0.2980611675632353, severity=Moderate
[19] dNBR=0.11648665530860162, severity=Low
[20] dNBR=0.17683907565882556, severity=Low
[21] dNBR=0.37225983944268565, severity=Moderate
[22] dNBR=0.05588583860900142, severity=Unburned / Recovered
[23] dNBR=0.189127876827824, severity=Low
[25] dNBR=0.0489464559874477, severity=Unburned / Recovered
[26] dNBR=0.26258438120833955, severity=Low
[27] dNBR=0.28499387888507266, severity=Moderate
[28] dNBR=0.3748409156266869, severity=Moderate
[29] dNBR=0.2804018023221509, severity=Moderate
[30] dNBR=0.15294586857144488, severity=Low
[31] dNBR=0.16726704022463953, severity=Low
[32] dNBR=0.14035193461629172, severity=Low
[33] dNBR=0.2081481866910882, severity=Low
[34] dNBR=0.11341277835377285, severity=Low
[35] dNBR=0.022130464060955386, severity=Unburned / Recovered
[36] dNBR=0.1486177526673414, severity=Low
[37] dNBR=0.1489306215596724, severity=Low
[38] dNBR=0.17537117264014943, severity=Low
[39] dNBR=0.20362924100203822, severity=Low
[40] dNBR=0.13148058346593106, severity=Low
[41] dNBR=0.473670843358416, severity=High
[44] dNBR=0.14559436372752246, severity=Low
[45] dNBR=0.5446424414300709, severity=High
[46] dNBR=0.3901144562279134, severity=Moderate
[47] dNBR=0.27551542098722837, severity=Moderate
[48] dNBR=0.2500458291776748, severity=Low
[49] dNBR=0.2823268741467533, severity=Moderate
[50] dNBR=0.31041034793440886, severity=Moderate
[51] dNBR=0.3209446046386498, severity=Moderate
[52] dNBR=0.5089731096097615, severity=High
[53] dNBR=0.37933263640038417, severity=Moderate
[55] dNBR=0.041274814241961964, severity=Unburned / Recovered
[56] dNBR=0.052701925771292416, severity=Unburned / Recovered
[58] dNBR=0.06580138263462512, severity=Unburned / Recovered
[59] dNBR=0.385759482904463, severity=Moderate
[60] dNBR=0.4288741166424766, severity=Moderate
[61] dNBR=0.5149492101256058, severity=High
[62] dNBR=0.011287563935175916, severity=Unburned / Recovered
[63] dNBR=0.16268250635985793, severity=Low
[64] dNBR=0.07162063293102759, severity=Unburned / Recovered
[65] dNBR=0.12428402027795837, severity=Low
[66] dNBR=0.0992352163134858, severity=Unburned / Recovered
[67] dNBR=0.08834985740747349, severity=Unburned / Recovered
[68] dNBR=0.048978251270595026, severity=Unburned / Recovered
[69] dNBR=0.10594771676683301, severity=Low
[70] dNBR=0.16294856445104228, severity=Low
[71] dNBR=0.20845901407131417, severity=Low
[72] dNBR=0.2288410733775906, severity=Low
[73] dNBR=0.09504821926099385, severity=Unburned / Recovered
[74] dNBR=0.3834911130883802, severity=Moderate
[75] dNBR=0.39675602726903325, severity=Moderate
[76] dNBR=0.25126775246039057, severity=Low
[77] dNBR=0.3486624503693183, severity=Moderate
[78] dNBR=0.17140161590559022, severity=Low
[81] dNBR=0.32057159991437073, severity=Moderate
[82] dNBR=0.16282136032244313, severity=Low
[83] dNBR=0.23094140351315595, severity=Low
[84] dNBR=0.4862101910072333, severity=High
[85] dNBR=0.08918304443615975, severity=Unburned / Recovered
[87] dNBR=0.45344197095373456, severity=High
[88] dNBR=0.2502936785872068, severity=Low
[89] dNBR=0.09589772636004013, severity=Unburned / Recovered
[90] dNBR=0.22426351883300413, severity=Low
[91] dNBR=0.3185368843204526, severity=Moderate
[92] dNBR=0.2992559031663778, severity=Moderate
[93] dNBR=0.33083746526616314, severity=Moderate
[94] dNBR=0.4673753141821067, severity=High
[95] dNBR=0.27974644593856823, severity=Moderate
[96] dNBR=0.2685972144786466, severity=Low
[97] dNBR=0.17618372805017593, severity=Low
[98] dNBR=0.4143085465704682, severity=Moderate
[99] dNBR=0.41114134208169567, severity=Moderate
[100] dNBR=0.41133250593447773, severity=Moderate
[101] dNBR=0.2261964609500427, severity=Low
[102] dNBR=0.18966383046934795, severity=Low
[103] dNBR=0.0725276658013552, severity=Unburned / Recovered
[104] dNBR=0.37722114812363133, severity=Moderate
[105] dNBR=0.3835942599173197, severity=Moderate
[106] dNBR=0.3179089346722388, severity=Moderate
[107] dNBR=0.21263777214098772, severity=Low
[108] dNBR=0.21420703174736713, severity=Low

In [ ]:
import ee
import pandas as pd
from datetime import datetime, timedelta

ee.Initialize(project="stubble-vision-ee")

In [ ]:
fire_events = df[df["label"] == 1].copy().reset_index(drop=True)
print("Total fire events:", len(fire_events))

Total fire events: 4122

In [ ]:
def compute_fire_severity(lat, lon, fire_date, buffer_m=500):
    try:
        point = ee.Geometry.Point([lon, lat])
        fire_dt = datetime.strptime(fire_date, "%Y-%m-%d")

        pre_start  = (fire_dt - timedelta(days=30)).strftime("%Y-%m-%d")
        pre_end    = (fire_dt - timedelta(days=5)).strftime("%Y-%m-%d")
        post_start = (fire_dt + timedelta(days=1)).strftime("%Y-%m-%d")
        post_end   = (fire_dt + timedelta(days=10)).strftime("%Y-%m-%d")

        s2 = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(point)
            .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 20))
        )

        pre = s2.filterDate(pre_start, pre_end).sort("CLOUDY_PIXEL_PERCENTAGE").first()
        post = s2.filterDate(post_start, post_end).sort("CLOUDY_PIXEL_PERCENTAGE").first()

        if pre is None or post is None:
            return None, "No Image"

        nbr_pre = pre.normalizedDifference(["B8", "B12"])
        nbr_post = post.normalizedDifference(["B8", "B12"])

        dnbr = nbr_pre.subtract(nbr_post).rename("dNBR")

        area = point.buffer(buffer_m)

        dnbr_dict = dnbr.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=area,
            scale=20,
            maxPixels=1e9,
            bestEffort=True
        ).getInfo()

        if dnbr_dict is None or "dNBR" not in dnbr_dict:
            return None, "No Data"

        dval = dnbr_dict["dNBR"]

        if dval < 0.10:
            sev = "Unburned / Recovered"
        elif dval < 0.27:
            sev = "Low"
        elif dval < 0.44:
            sev = "Moderate"
        else:
            sev = "High"

        return dval, sev

    except Exception as e:
        return None, f"Error"

In [ ]:
import os

OUTPUT_DIR = "/content/drive/MyDrive/stubble_vision/results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("✅ Results directory ready:", OUTPUT_DIR)

✅ Results directory ready: /content/drive/MyDrive/stubble_vision/results

In [ ]:
BATCH_SIZE = 50          # do NOT increase
START_INDEX = 0          # change if resuming
END_INDEX = len(fire_events)

OUTPUT_DIR = "/content/drive/MyDrive/stubble_vision/results"

In [ ]:
results = []

for i in range(START_INDEX, END_INDEX):
    row = fire_events.iloc[i]

    dnbr_val, severity = compute_fire_severity(
        row["latitude"],
        row["longitude"],
        row["acq_date"]
    )

    results.append({
        "fire_id": i,
        "latitude": row["latitude"],
        "longitude": row["longitude"],
        "fire_date": row["acq_date"],
        "dNBR": dnbr_val,
        "severity": severity
    })

    # Progress log
    if (i + 1) % 10 == 0:
        print(f"Processed {i + 1} / {END_INDEX}")

    # Save batch
    if (i + 1) % BATCH_SIZE == 0:
        batch_df = pd.DataFrame(results)
        batch_path = f"{OUTPUT_DIR}/severity_batch_{i+1}.csv"
        batch_df.to_csv(batch_path, index=False)
        print(f"Saved {batch_path}")
        results = []  # clear memory

Processed 10 / 4122
Processed 20 / 4122
Processed 30 / 4122
Processed 40 / 4122
Processed 50 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_50.csv
Processed 60 / 4122
Processed 70 / 4122
Processed 80 / 4122
Processed 90 / 4122
Processed 100 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_100.csv
Processed 110 / 4122
Processed 120 / 4122
Processed 130 / 4122
Processed 140 / 4122
Processed 150 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_150.csv
Processed 160 / 4122
Processed 170 / 4122
Processed 180 / 4122
Processed 190 / 4122
Processed 200 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_200.csv
Processed 210 / 4122
Processed 220 / 4122
Processed 230 / 4122
Processed 240 / 4122
Processed 250 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_250.csv
Processed 260 / 4122
Processed 270 / 4122
Processed 280 / 4122
Processed 290 / 4122
Processed 300 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_300.csv
Processed 310 / 4122
Processed 320 / 4122
Processed 330 / 4122
Processed 340 / 4122
Processed 350 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_350.csv
Processed 360 / 4122
Processed 370 / 4122
Processed 380 / 4122
Processed 390 / 4122
Processed 400 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_400.csv
Processed 410 / 4122
Processed 420 / 4122
Processed 430 / 4122
Processed 440 / 4122
Processed 450 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_450.csv
Processed 460 / 4122
Processed 470 / 4122
Processed 480 / 4122
Processed 490 / 4122
Processed 500 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_500.csv
Processed 510 / 4122
Processed 520 / 4122
Processed 530 / 4122
Processed 540 / 4122
Processed 550 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_550.csv
Processed 560 / 4122
Processed 570 / 4122
Processed 580 / 4122
Processed 590 / 4122
Processed 600 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_600.csv
Processed 610 / 4122
Processed 620 / 4122
Processed 630 / 4122
Processed 640 / 4122
Processed 650 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_650.csv
Processed 660 / 4122
Processed 670 / 4122
Processed 680 / 4122
Processed 690 / 4122
Processed 700 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_700.csv
Processed 710 / 4122
Processed 720 / 4122
Processed 730 / 4122
Processed 740 / 4122
Processed 750 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_750.csv
Processed 760 / 4122
Processed 770 / 4122
Processed 780 / 4122
Processed 790 / 4122
Processed 800 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_800.csv
Processed 810 / 4122
Processed 820 / 4122
Processed 830 / 4122
Processed 840 / 4122
Processed 850 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_850.csv
Processed 860 / 4122
Processed 870 / 4122
Processed 880 / 4122
Processed 890 / 4122
Processed 900 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_900.csv
Processed 910 / 4122
Processed 920 / 4122
Processed 930 / 4122
Processed 940 / 4122
Processed 950 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_950.csv
Processed 960 / 4122
Processed 970 / 4122
Processed 980 / 4122
Processed 990 / 4122
Processed 1000 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1000.csv
Processed 1010 / 4122
Processed 1020 / 4122
Processed 1030 / 4122
Processed 1040 / 4122
Processed 1050 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1050.csv
Processed 1060 / 4122
Processed 1070 / 4122
Processed 1080 / 4122
Processed 1090 / 4122
Processed 1100 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1100.csv
Processed 1110 / 4122
Processed 1120 / 4122
Processed 1130 / 4122
Processed 1140 / 4122
Processed 1150 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1150.csv
Processed 1160 / 4122
Processed 1170 / 4122
Processed 1180 / 4122
Processed 1190 / 4122
Processed 1200 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1200.csv
Processed 1210 / 4122
Processed 1220 / 4122
Processed 1230 / 4122
Processed 1240 / 4122
Processed 1250 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1250.csv
Processed 1260 / 4122
Processed 1270 / 4122
Processed 1280 / 4122
Processed 1290 / 4122
Processed 1300 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1300.csv
Processed 1310 / 4122
Processed 1320 / 4122
Processed 1330 / 4122
Processed 1340 / 4122
Processed 1350 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1350.csv
Processed 1360 / 4122
Processed 1370 / 4122
Processed 1380 / 4122
Processed 1390 / 4122
Processed 1400 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1400.csv
Processed 1410 / 4122
Processed 1420 / 4122
Processed 1430 / 4122
Processed 1440 / 4122
Processed 1450 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1450.csv
Processed 1460 / 4122
Processed 1470 / 4122
Processed 1480 / 4122
Processed 1490 / 4122
Processed 1500 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1500.csv
Processed 1510 / 4122
Processed 1520 / 4122
Processed 1530 / 4122
Processed 1540 / 4122
Processed 1550 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1550.csv
Processed 1560 / 4122
Processed 1570 / 4122
Processed 1580 / 4122
Processed 1590 / 4122
Processed 1600 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1600.csv
Processed 1610 / 4122
Processed 1620 / 4122
Processed 1630 / 4122
Processed 1640 / 4122
Processed 1650 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1650.csv
Processed 1660 / 4122
Processed 1670 / 4122
Processed 1680 / 4122
Processed 1690 / 4122
Processed 1700 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1700.csv
Processed 1710 / 4122
Processed 1720 / 4122
Processed 1730 / 4122
Processed 1740 / 4122
Processed 1750 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1750.csv
Processed 1760 / 4122
Processed 1770 / 4122
Processed 1780 / 4122
Processed 1790 / 4122
Processed 1800 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1800.csv
Processed 1810 / 4122
Processed 1820 / 4122
Processed 1830 / 4122
Processed 1840 / 4122
Processed 1850 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1850.csv
Processed 1860 / 4122
Processed 1870 / 4122
Processed 1880 / 4122
Processed 1890 / 4122
Processed 1900 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1900.csv
Processed 1910 / 4122
Processed 1920 / 4122
Processed 1930 / 4122
Processed 1940 / 4122
Processed 1950 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_1950.csv
Processed 1960 / 4122
Processed 1970 / 4122
Processed 1980 / 4122
Processed 1990 / 4122
Processed 2000 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2000.csv
Processed 2010 / 4122
Processed 2020 / 4122
Processed 2030 / 4122
Processed 2040 / 4122
Processed 2050 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2050.csv
Processed 2060 / 4122
Processed 2070 / 4122
Processed 2080 / 4122
Processed 2090 / 4122
Processed 2100 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2100.csv
Processed 2110 / 4122
Processed 2120 / 4122
Processed 2130 / 4122
Processed 2140 / 4122
Processed 2150 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2150.csv
Processed 2160 / 4122
Processed 2170 / 4122
Processed 2180 / 4122
Processed 2190 / 4122
Processed 2200 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2200.csv
Processed 2210 / 4122
Processed 2220 / 4122
Processed 2230 / 4122
Processed 2240 / 4122
Processed 2250 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2250.csv
Processed 2260 / 4122
Processed 2270 / 4122
Processed 2280 / 4122
Processed 2290 / 4122
Processed 2300 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2300.csv
Processed 2310 / 4122
Processed 2320 / 4122
Processed 2330 / 4122
Processed 2340 / 4122
Processed 2350 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2350.csv
Processed 2360 / 4122
Processed 2370 / 4122
Processed 2380 / 4122
Processed 2390 / 4122
Processed 2400 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2400.csv
Processed 2410 / 4122
Processed 2420 / 4122
Processed 2430 / 4122
Processed 2440 / 4122
Processed 2450 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2450.csv
Processed 2460 / 4122
Processed 2470 / 4122
Processed 2480 / 4122
Processed 2490 / 4122
Processed 2500 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2500.csv
Processed 2510 / 4122
Processed 2520 / 4122
Processed 2530 / 4122
Processed 2540 / 4122
Processed 2550 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2550.csv
Processed 2560 / 4122
Processed 2570 / 4122
Processed 2580 / 4122
Processed 2590 / 4122
Processed 2600 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2600.csv
Processed 2610 / 4122
Processed 2620 / 4122
Processed 2630 / 4122
Processed 2640 / 4122
Processed 2650 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2650.csv
Processed 2660 / 4122
Processed 2670 / 4122
Processed 2680 / 4122
Processed 2690 / 4122
Processed 2700 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2700.csv
Processed 2710 / 4122
Processed 2720 / 4122
Processed 2730 / 4122
Processed 2740 / 4122
Processed 2750 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2750.csv
Processed 2760 / 4122
Processed 2770 / 4122
Processed 2780 / 4122
Processed 2790 / 4122
Processed 2800 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2800.csv
Processed 2810 / 4122
Processed 2820 / 4122
Processed 2830 / 4122
Processed 2840 / 4122
Processed 2850 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2850.csv
Processed 2860 / 4122
Processed 2870 / 4122
Processed 2880 / 4122

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

Processed 2890 / 4122
Processed 2900 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2900.csv
Processed 2910 / 4122
Processed 2920 / 4122
Processed 2930 / 4122
Processed 2940 / 4122
Processed 2950 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_2950.csv
Processed 2960 / 4122
Processed 2970 / 4122
Processed 2980 / 4122
Processed 2990 / 4122
Processed 3000 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3000.csv
Processed 3010 / 4122
Processed 3020 / 4122
Processed 3030 / 4122
Processed 3040 / 4122
Processed 3050 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3050.csv
Processed 3060 / 4122
Processed 3070 / 4122
Processed 3080 / 4122
Processed 3090 / 4122
Processed 3100 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3100.csv
Processed 3110 / 4122
Processed 3120 / 4122
Processed 3130 / 4122
Processed 3140 / 4122
Processed 3150 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3150.csv
Processed 3160 / 4122
Processed 3170 / 4122
Processed 3180 / 4122
Processed 3190 / 4122
Processed 3200 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3200.csv
Processed 3210 / 4122
Processed 3220 / 4122
Processed 3230 / 4122
Processed 3240 / 4122
Processed 3250 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3250.csv
Processed 3260 / 4122
Processed 3270 / 4122
Processed 3280 / 4122
Processed 3290 / 4122
Processed 3300 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3300.csv
Processed 3310 / 4122
Processed 3320 / 4122
Processed 3330 / 4122
Processed 3340 / 4122
Processed 3350 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3350.csv
Processed 3360 / 4122
Processed 3370 / 4122
Processed 3380 / 4122
Processed 3390 / 4122
Processed 3400 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3400.csv
Processed 3410 / 4122
Processed 3420 / 4122
Processed 3430 / 4122
Processed 3440 / 4122
Processed 3450 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3450.csv
Processed 3460 / 4122
Processed 3470 / 4122
Processed 3480 / 4122
Processed 3490 / 4122
Processed 3500 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3500.csv
Processed 3510 / 4122
Processed 3520 / 4122
Processed 3530 / 4122
Processed 3540 / 4122
Processed 3550 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3550.csv
Processed 3560 / 4122
Processed 3570 / 4122
Processed 3580 / 4122
Processed 3590 / 4122
Processed 3600 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3600.csv
Processed 3610 / 4122
Processed 3620 / 4122
Processed 3630 / 4122
Processed 3640 / 4122
Processed 3650 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3650.csv
Processed 3660 / 4122
Processed 3670 / 4122
Processed 3680 / 4122
Processed 3690 / 4122
Processed 3700 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3700.csv
Processed 3710 / 4122
Processed 3720 / 4122
Processed 3730 / 4122
Processed 3740 / 4122
Processed 3750 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3750.csv
Processed 3760 / 4122
Processed 3770 / 4122
Processed 3780 / 4122
Processed 3790 / 4122
Processed 3800 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3800.csv
Processed 3810 / 4122
Processed 3820 / 4122
Processed 3830 / 4122
Processed 3840 / 4122
Processed 3850 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3850.csv
Processed 3860 / 4122
Processed 3870 / 4122
Processed 3880 / 4122
Processed 3890 / 4122
Processed 3900 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3900.csv
Processed 3910 / 4122
Processed 3920 / 4122
Processed 3930 / 4122
Processed 3940 / 4122
Processed 3950 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_3950.csv
Processed 3960 / 4122
Processed 3970 / 4122
Processed 3980 / 4122
Processed 3990 / 4122
Processed 4000 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_4000.csv
Processed 4010 / 4122
Processed 4020 / 4122
Processed 4030 / 4122
Processed 4040 / 4122
Processed 4050 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_4050.csv
Processed 4060 / 4122
Processed 4070 / 4122
Processed 4080 / 4122
Processed 4090 / 4122
Processed 4100 / 4122
Saved /content/drive/MyDrive/stubble_vision/results/severity_batch_4100.csv
Processed 4110 / 4122
Processed 4120 / 4122

In [ ]:
if results:
    final_df = pd.DataFrame(results)
    final_path = f"{OUTPUT_DIR}/severity_final.csv"
    final_df.to_csv(final_path, index=False)
    print(f"Saved {final_path}")

Saved /content/drive/MyDrive/stubble_vision/results/severity_final.csv

In [ ]:
import os

RESULTS_DIR = "/content/drive/MyDrive/stubble_vision/results"
files = sorted([f for f in os.listdir(RESULTS_DIR) if f.endswith(".csv")])

print("Number of result files:", len(files))
files[:]

Number of result files: 83

['severity_batch_100.csv',
 'severity_batch_1000.csv',
 'severity_batch_1050.csv',
 'severity_batch_1100.csv',
 'severity_batch_1150.csv',
 'severity_batch_1200.csv',
 'severity_batch_1250.csv',
 'severity_batch_1300.csv',
 'severity_batch_1350.csv',
 'severity_batch_1400.csv',
 'severity_batch_1450.csv',
 'severity_batch_150.csv',
 'severity_batch_1500.csv',
 'severity_batch_1550.csv',
 'severity_batch_1600.csv',
 'severity_batch_1650.csv',
 'severity_batch_1700.csv',
 'severity_batch_1750.csv',
 'severity_batch_1800.csv',
 'severity_batch_1850.csv',
 'severity_batch_1900.csv',
 'severity_batch_1950.csv',
 'severity_batch_200.csv',
 'severity_batch_2000.csv',
 'severity_batch_2050.csv',
 'severity_batch_2100.csv',
 'severity_batch_2150.csv',
 'severity_batch_2200.csv',
 'severity_batch_2250.csv',
 'severity_batch_2300.csv',
 'severity_batch_2350.csv',
 'severity_batch_2400.csv',
 'severity_batch_2450.csv',
 'severity_batch_250.csv',
 'severity_batch_2500.csv',
 'severity_batch_2550.csv',
 'severity_batch_2600.csv',
 'severity_batch_2650.csv',
 'severity_batch_2700.csv',
 'severity_batch_2750.csv',
 'severity_batch_2800.csv',
 'severity_batch_2850.csv',
 'severity_batch_2900.csv',
 'severity_batch_2950.csv',
 'severity_batch_300.csv',
 'severity_batch_3000.csv',
 'severity_batch_3050.csv',
 'severity_batch_3100.csv',
 'severity_batch_3150.csv',
 'severity_batch_3200.csv',
 'severity_batch_3250.csv',
 'severity_batch_3300.csv',
 'severity_batch_3350.csv',
 'severity_batch_3400.csv',
 'severity_batch_3450.csv',
 'severity_batch_350.csv',
 'severity_batch_3500.csv',
 'severity_batch_3550.csv',
 'severity_batch_3600.csv',
 'severity_batch_3650.csv',
 'severity_batch_3700.csv',
 'severity_batch_3750.csv',
 'severity_batch_3800.csv',
 'severity_batch_3850.csv',
 'severity_batch_3900.csv',
 'severity_batch_3950.csv',
 'severity_batch_400.csv',
 'severity_batch_4000.csv',
 'severity_batch_4050.csv',
 'severity_batch_4100.csv',
 'severity_batch_450.csv',
 'severity_batch_50.csv',
 'severity_batch_500.csv',
 'severity_batch_550.csv',
 'severity_batch_600.csv',
 'severity_batch_650.csv',
 'severity_batch_700.csv',
 'severity_batch_750.csv',
 'severity_batch_800.csv',
 'severity_batch_850.csv',
 'severity_batch_900.csv',
 'severity_batch_950.csv',
 'severity_final.csv']

In [ ]:
import pandas as pd

dfs = []

for f in files:
    path = os.path.join(RESULTS_DIR, f)
    dfs.append(pd.read_csv(path))

severity_all = pd.concat(dfs, ignore_index=True)

print("Merged severity shape:", severity_all.shape)
severity_all.head()

Merged severity shape: (4122, 6)

   fire_id  latitude  longitude   fire_date      dNBR              severity
0       50  29.90912   77.87334  2025-11-01  0.041275  Unburned / Recovered
1       51  29.91256   77.87257  2025-11-01  0.052702  Unburned / Recovered
2       52  29.98193   76.76251  2025-11-01  0.065801  Unburned / Recovered
3       53  29.98950   75.82626  2025-11-01  0.385759              Moderate
4       54  30.00345   76.08458  2025-11-01  0.428874              Moderate

In [ ]:
severity_all["severity"].value_counts()

severity
Moderate                1466
Low                     1410
High                     647
Unburned / Recovered     593
Error                      6
Name: count, dtype: int64

In [ ]:
# make sure severity_all exists
print("severity_all shape:", severity_all.shape)

# filter only valid severity classes
valid_severity = severity_all[
    severity_all["severity"].isin(
        ["Unburned / Recovered", "Low", "Moderate", "High"]
    )
].copy()

print("Valid severity rows:", len(valid_severity))

severity_all shape: (4122, 6)
Valid severity rows: 4116

In [ ]:
severity_counts = valid_severity["severity"].value_counts()
severity_percent = severity_counts / severity_counts.sum() * 100

severity_summary = pd.DataFrame({
    "count": severity_counts,
    "percentage (%)": severity_percent.round(2)
})

severity_summary

                      count  percentage (%)
severity
Moderate               1466           35.62
Low                    1410           34.26
High                    647           15.72
Unburned / Recovered    593           14.41

In [ ]:
# pick first Low severity fire
sample_fire = valid_severity[valid_severity["severity"] == "Low"].iloc[0]

lat = sample_fire["latitude"]
lon = sample_fire["longitude"]
fire_date = sample_fire["fire_date"]

lat, lon, fire_date

(np.float64(29.7423), np.float64(74.42926), '2025-11-01')

In [ ]:
from datetime import datetime, timedelta
import ee

point = ee.Geometry.Point([lon, lat])
fire_dt = datetime.strptime(fire_date, "%Y-%m-%d")

pre_start  = (fire_dt - timedelta(days=30)).strftime("%Y-%m-%d")
pre_end    = (fire_dt - timedelta(days=5)).strftime("%Y-%m-%d")
post_start = (fire_dt + timedelta(days=1)).strftime("%Y-%m-%d")
post_end   = (fire_dt + timedelta(days=10)).strftime("%Y-%m-%d")

s2 = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
    .filterBounds(point)
    .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 20))
)

pre = s2.filterDate(pre_start, pre_end).sort("CLOUDY_PIXEL_PERCENTAGE").first()
post = s2.filterDate(post_start, post_end).sort("CLOUDY_PIXEL_PERCENTAGE").first()

In [ ]:
nbr_pre = pre.normalizedDifference(["B8", "B12"])
nbr_post = post.normalizedDifference(["B8", "B12"])
dnbr = nbr_pre.subtract(nbr_post).rename("dNBR")

In [ ]:
# Visualization styles
nbr_vis = {
    "min": -0.5,
    "max": 0.8,
    "palette": ["brown", "yellow", "green"]
}

dnbr_vis = {
    "min": -0.1,
    "max": 0.6,
    "palette": ["green", "yellow", "orange", "red"]
}

In [ ]:
import geemap

Map = geemap.Map(center=[lat, lon], zoom=12)

Map.addLayer(nbr_pre, nbr_vis, "NBR Pre-Fire")
Map.addLayer(nbr_post, nbr_vis, "NBR Post-Fire")
Map.addLayer(dnbr, dnbr_vis, "dNBR (Severity)")

Map.addLayer(point, {"color": "blue"}, "Fire Location")

Map

Map(center=[np.float64(29.7423), np.float64(74.42926)], controls=(WidgetControl(options=['position', 'transpar…